//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioEtherMonitor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Performer> PerformerSet { get; set; }
        public virtual DbSet<Song> SongSet { get; set; }
        public virtual DbSet<Country> CountrySet { get; set; }
        public virtual DbSet<CountryGroup> CountryGroupSet { get; set; }
        public virtual DbSet<Language> LanguageSet { get; set; }
        public virtual DbSet<Quote> QuoteSet { get; set; }
        public virtual DbSet<Performance> PerformanceSet { get; set; }
        public virtual DbSet<RadioStation> RadioStationSet { get; set; }
    }
}
